export enum Category {
  SUGGESTION_FOR_IMPROVEMENT = "SUGGESTION_FOR_IMPROVEMENT",
  BUG_REPORT = "BUG_REPORT",
  FEATURE_REQUEST = "FEATURE_REQUEST",
  TRAINING_REQUEST = "TRAINING_REQUEST",
  OTHER = "OTHER",
}
