export enum Role {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  CUSTOMER_REQUEST_REVISER = 'CUSTOMER_REQUEST_REVISER',
  CAPACITY_PLANNER = 'CAPACITY_PLANNER',
  TASK_REVISER = 'TASK_REVISER',
  PROJECT_PLANNER = 'PROJECT_PLANNER',
}
